name: Export

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export using Godot Export Action (v7)
        uses: firebelley/godot-export@v7.0.0
        with:
          # Godot Editor (Mono) 4.5.1 download
          godot_executable_download_url: "https://downloads.tuxfamily.org/godotengine/4.5.1/mono/Godot_v4.5.1-stable_mono_linux.x86_64.zip"

          # Export Templates (Mono) 4.5.1 download
          godot_export_templates_download_url: "https://downloads.tuxfamily.org/godotengine/4.5.1/mono/Godot_v4.5.1-stable_mono_export_templates.tpz"

          # Export your presets by name (must match your export_presets.cfg)
          presets_to_export: |
            Windows
            HTML5

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: build/