name: Export

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export using Godot Export Action (v7)
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: "https://downloads.godotengine.org/?version=4.5.1&flavor=stable&slug=mono_linux_x86_64.zip&platform=linux.64"
          godot_export_templates_download_url: "https://downloads.godotengine.org/?version=4.5.1&flavor=stable&slug=mono_export_templates.tpz&platform=templates"

          presets_to_export: |
            Windows

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: exports/GameJamPlus2025Project.exe

      - name: Install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip -d butler
          sudo mv butler/butler /usr/local/bin/butler
          butler --version

      - name: Upload Windows build to itch.io
        run: |
          # Push the entire exported Windows folder
          butler push exports yudhistira-anggara/game-jam-plus-2025-project:windows
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}
