name: Export

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export using Godot Export Action (v7)
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: "https://downloads.godotengine.org/?version=4.5.1&flavor=stable&slug=mono_linux_x86_64.zip&platform=linux.64"
          godot_export_templates_download_url: "https://downloads.godotengine.org/?version=4.5.1&flavor=stable&slug=mono_export_templates.tpz&platform=templates"

          # Must match the names in export_presets.cfg
          presets_to_export: |
            Windows
            HTML5

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: exports/
